version: '3.3'

services:
  db:
    image: postgres:11
    environment:
      - PGDATA=/var/lib/postgresql/data/pgdata
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=password
    ports:
      - "5432:5432"

  server:
    build:
      context: .
      dockerfile: server/Dockerfile
    environment:
      - RAILS_ENV=development
      - RACK_ENV=development
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=password
    depends_on:
      - db
    volumes:
      - "./server:/app"
    ports:
      - "3000:3000"
    command:
      - RUN rake db:create
      - RUN rails db:migrate
      - rails s -p 3000 -b '0.0.0.0'

  client:
    build:
      context: .
      dockerfile: client/Dockerfile
    depends_on:
      - server
    volumes:
      - "./client:/app"
    ports:
      - "4200:4200"
    command: ng serve
